config/routes.rb
Blog::Application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "newsletters/newsletter_sign_up"

  root :to => "statics#home"

  get "/about", to: 'statics#about'
  get 'feed', to: 'posts#feed', as: 'feed'
  get "backpacking-brands", to: 'statics#brands', as: 'brands'
  get 'results', to: 'statics#results', as: 'results'

  resources :gear_guides, path: 'gear-guides', except: :index
  resources :posts do
    collection do
      get 'section/:section', to: 'posts#section', as: 'section', constraints: proc { |req| ['backpacking', 'gear', 'food', 'photography'].include?(req.params[:section]) }
    end
  end
  resources :contact, only: [:new, :create], path: 'contact'
  resources :categories, except: :index
  resources :retailers, except: [:index, :show]
  resources :internal_categories, except: [:index, :show]

end

app/models/gear_guide.rb
class GearGuide < ActiveRecord::Base
  belongs_to :user
  has_many :internal_categorizations, as: :internal_categorizable, dependent: :destroy
  has_many :internal_categories, :through => :internal_categorizations

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/gear_guides_controller.rb
class GearGuidesController < ApplicationController
  before_action :set_gear_guide, only: [:show, :edit, :update, :destroy]

  include PostCount # for unless bot? method in private

  # GET /gear_guides
  # GET /gear_guides.json
  # def index
  #   @gear_guides = GearGuide.all
  # end

  # GET /gear_guides/1
  # GET /gear_guides/1.json
  def show
    impression_count(@gear_guide)
    @popular = GearGuide.order('view_count DESC').where('id != ?', @gear_guide.id).first(4)
  end

  # GET /gear_guides/new
  def new
    @gear_guide = GearGuide.new
  end

  # GET /gear_guides/1/edit
  def edit
  end

  # POST /gear_guides
  # POST /gear_guides.json
  def create
    @gear_guide = GearGuide.new(gear_guide_params)
    @gear_guide.user_id = current_user.id

    respond_to do |format|
      if @gear_guide.save
        format.html { redirect_to @gear_guide, notice: 'Gear guide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gear_guide }
      else
        format.html { render action: 'new' }
        format.json { render json: @gear_guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gear_guides/1
  # PATCH/PUT /gear_guides/1.json
  def update
    respond_to do |format|
      @gear_guide.user_id = current_user.id
      if @gear_guide.update(gear_guide_params)
        format.html { redirect_to @gear_guide, notice: 'Gear guide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gear_guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gear_guides/1
  # DELETE /gear_guides/1.json
  def destroy
    @gear_guide.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear_guide
      @gear_guide = GearGuide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_guide_params
      params.require(:gear_guide).permit(:user_id, :title, :content, :meta_description, internal_category_ids: [])
    end

    def impression_count(guide)
      unless bot?(request.user_agent)
        guide.update_attributes(view_count: guide.view_count + 1)
      end
    end
end

app/helpers/gear_guides_helper.rb
module GearGuidesHelper
end

app/views/gear_guides/_form.html.erb
<%= form_for(@gear_guide) do |f| %>
  <% if @gear_guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gear_guide.errors.count, "error") %> prohibited this gear_guide from being saved:</h2>

      <ul>
      <% @gear_guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well">

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <br>
    <div class="well">
      <ul>
        <li>Main image is 300px wide / gets 'gear-guide-img' class / right aligned</li>
        <li>Image needs to be uploaded to app assets</li>
        <li>All anchors need the 'anchor' class</li>
        <li>Jump To box gets wrapped in a div w/ class 'well'</li>
        <li>'Jump To' gets p > strong</li>
        <li>Available CSS classes: no-border center</li>
        <li>Each gear guide needs an image in gear-guides/thumbnails with filename as title.parameterize</li>
      </ul>
    </div>
    <div class="field">
      <%= f.label :meta_description %><br>
      <%= f.text_field :meta_description %>
    </div>
    <h3>Internal Categories</h3>
    <%= hidden_field_tag "gear_guide[internal_category_ids][]", nil %>
    <% InternalCategory.find_each do |category| %>
      <%= check_box_tag "gear_guide[internal_category_ids][]", category.id, @gear_guide.internal_category_ids.include?(category.id), id: dom_id(category) %>
      <%= label_tag dom_id(category), category.name %><br>
    <% end %>
    <br>
    <div class="actions">
      <%= f.submit 'Create Gear Guide', class: 'my-btn' %>
    </div>
  </div>
<% end %>

<script>CKEDITOR.replace('gear_guide[content]');</script>

app/views/gear_guides/edit.html.erb
<h1>Editing <%= @gear_guide.title %> Gear Guide</h1>

<%= render 'form' %>

app/views/gear_guides/index.html.erb
<h1>Listing gear_guides</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Meta description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gear_guides.each do |gear_guide| %>
      <tr>
        <td><%= gear_guide.user_id %></td>
        <td><%= gear_guide.title %></td>
        <td><%= gear_guide.content %></td>
        <td><%= gear_guide.meta_description %></td>
        <td><%= link_to 'Show', gear_guide %></td>
        <td><%= link_to 'Edit', edit_gear_guide_path(gear_guide) %></td>
        <td><%= link_to 'Destroy', gear_guide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gear guide', new_gear_guide_path %>

app/views/gear_guides/new.html.erb
<h1>New Gear Guide</h1>

<%= render 'form' %>

app/views/gear_guides/show.html.erb
<% provide(:title, @gear_guide.title) %>
<% provide(:desc, @gear_guide.meta_description) %>
<% provide(:canonical, gear_guide_url(@gear_guide)) %>
<% content_for :head do %>
  <meta property="og:title" content="<%= @gear_guide.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:description" content="<%= @gear_guide.meta_description %>" />
  <meta property="og:site_name" content="Backpacking Talk" />
  <meta property="og:url" content="<%= gear_guide_url(@gear_guide) %>" />
  <meta property="og:image" content="/assets/gear-guide/<%= @gear_guide.title.parameterize %>.jpg" />

  <meta property="article:published_time" content="<%= @gear_guide.created_at %>" />
  <meta property="article:modified_time" content="<%= @gear_guide.updated_at %>" />
  <meta property="article:author" content="Stuart Morris" />
  <meta property="article:section" content="Outdoors" />
<% end %>

<div itemscope itemtype="http://schema.org/Article">

  <div class="social-arrow">
    <%= image_tag("share.png", alt: 'show share buttons', title: 'show share buttons', class: 'social-arrow-img')  %>
  </div>

  <div class="social-bar">
    <div class="social-button">
      <div id="fb-root"></div>
      <div class="fb-like" data-href="<%= gear_guide_url(@gear_guide) %>" data-send="false" data-layout="box_count" data-width="55" data-show-faces="false"></div>
    </div>
    <div class="social-button">
      <su:badge layout="5" location="<%= gear_guide_url(@gear_guide) %>"></su:badge>
    </div>
    <div class="social-button">
      <div class="g-plusone" data-size="tall" data-href="<%= gear_guide_url(@gear_guide) %>"></div>
    </div>
    <div class="social-button">
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= gear_guide_url(@gear_guide) %>" data-via="stuwashere" data-count="vertical">Tweet</a>
    </div>
    <div class="social-button">
      <a href="//pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" ><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
    </div>
  </div>

  <h1 class="gear-guide-h1" itemprop="headline"><%= @gear_guide.title %></h1>
  <meta itemprop="author" content="Stuart Morris">
  <meta itemprop="wordCount" content="<%= strip_tags(@gear_guide.content).scan(/[\w-]+/).size %>">

  <div class="meta-well">
    <span class="post-meta-unit">
      <span class="gear-guide-published">
        <i class="icon-calendar"></i>
        <strong>Published: </strong>
        <time itemprop="datePublished" datetime="<%= @gear_guide.created_at %>">
          <%= content_tag :span, pretty_date(@gear_guide.created_at) %>
        </time>
      </span>
    </span>

    <span class="post-meta-unit">
      <span class="gear-guide-updated">
        <i class="icon-edit"></i>
        <strong>Last Updated: </strong>
        <time itemprop="dateModified" datetime="<%= @gear_guide.updated_at %>">
          <%= content_tag :span, pretty_date(@gear_guide.updated_at) %>
        </time>
      </span>
    </span>

    <% if can? :edit, @gear_guide %>

      <span class="post-meta-unit">
        <i class="icon-edit"></i>
        <%= link_to 'Edit', edit_gear_guide_path(@gear_guide) %>
      </span>

      <span class="post-meta-unit">
        <i class="icon-remove"></i>
        <%= link_to 'Delete', @gear_guide, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>

    <% end %>

  </div>

  <div class="gear-guide-well">
    Did we get something in this gear guide wrong? <%= link_to "Let us know!", new_contact_path %>
  </div>

  <% if @gear_guide.internal_categories.present? %>

    <div class="gear-guide-well">

      <b>Find brands that make <%= @gear_guide.internal_categories.map { |gg| link_to gg.name, brands_path(gear: gg.id) }.join(', ').html_safe %></b>

    </div>

  <% end %>

  <div class="gear-guide-content"  itemprop="articleBody">
    <%= @gear_guide.content.html_safe %>
  </div>

  <h2>Popular Gear Guides</h2>

  <div class="bottom-of-post">

    <% @popular.each_with_index do |guide, i| %>
      <div class="related-div <%= i == 3 ? 'last-related-pic' : '' %>">
        <a href="<%= gear_guide_path(guide) %>">
          <%= image_tag "/gear-guide/thumbnails/#{guide.title.parameterize}.jpg", alt: guide.title, class: "related-post-pic" %>
          <%= content_tag :span, guide.title, class: 'related-gear-guide-title' %>
        </a>
      </div>
    <% end %>

  </div>

</div>