config/routes.rb
Blog::Application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "newsletters/newsletter_sign_up"

  root :to => "statics#home"

  get "/about", to: 'statics#about'
  get 'feed', to: 'posts#feed', as: 'feed'
  get "backpacking-brands", to: 'statics#brands', as: 'brands'
  get 'results', to: 'statics#results', as: 'results'

  resources :gear_guides, path: 'gear-guides', except: :index
  resources :posts do
    collection do
      get 'section/:section', to: 'posts#section', as: 'section', constraints: proc { |req| ['backpacking', 'gear', 'food', 'photography'].include?(req.params[:section]) }
    end
  end
  resources :contact, only: [:new, :create], path: 'contact'
  resources :categories, except: :index
  resources :retailers, except: [:index, :show]
  resources :internal_categories, except: [:index, :show]

end

app/views/shared/_alerts.html.erb
<div>
  <% flash.each do |key, value| %>
    <% if value.is_a? Array %>
      <% value.each do |message| %>
        <% if message == value.last %>
          <div class="<%= flash_class(key) %> fade in alert-last">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <%= message %>
          </div>
        <% else %>
          <div class="<%= flash_class(key) %> fade in">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <%= message %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="<%= flash_class(key) %> fade in alert-last">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_group.html.erb
<div class="group-row">
  <% group.each_with_index do |post, i| %>
    <div class="result-post <%= i == 0 ? "result-post-margin" : "" %>">
      <div class="result-pic">
        <%= link_to image_tag(post.pic_medium_url, alt: post.picture_alt_text), post_path(post), class: 'result-pic'  %>
      </div>
      <h2><%= link_to post.title, post_path(post), class: "result-title" %></h2>
      <% unless params[:controller] == "posts" && params[:action] == "section" %>
        <span class="result-section">
          <%= link_to post.section.titleize, section_posts_path(section: post.section) %>
        </span>
      <% end %>
      <span class="result-date">
        <i class="icon-calendar"></i>
        <i><%= pretty_date(post.created_at) %></i>
      </span>
      <i class="icon-tags"></i>
      <%= post.categories.map { |c|
            "<a href=\"#{category_path(c)}\" class=\"result-category\">#{c.name}</a>"
           }.join(', ').html_safe %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav pull-left header-sections">

        <% ['backpacking', 'gear', 'photos', 'food'].each do |section| %>

          <% if Post.where("section = ?", section).present? %>

            <li class="dropdown">
              <a class="dropdown-toggle"
                 data-toggle="dropdown"
                 href="#">
                  <%= section.titleize %>
                  <b class="caret"></b>
                </a>
              <ul class="dropdown-menu section-dropdown">
                <%= render partial: 'shared/tabs/post', collection: Post.where("section = ?", section).order('created_at DESC').first(3) %>
                <li class="section-read-more">
                  <strong>
                    <%= link_to "More From #{section.titleize} <i class=\"icon-arrow-right icon-white\"></i>".html_safe, section_posts_path(section: section) %>
                  </strong>
                </li>
              </ul>
            </li>

          <% end %>

        <% end %>

      </ul>

      <ul class="nav pull-left header-evergreen">

        <li class="dropdown">
          <a class="dropdown-toggle"
             data-toggle="dropdown"
             href="#">
              Gear Guides
              <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <% GearGuide.find_each do |guide| %>
              <li>
                <%= link_to guide.title, gear_guide_path(guide) %>
              </li>
            <% end %>
          </ul>
        </li>

        <li class="brands"><%= link_to "Backpacking Brands", brands_path, class: 'brands-toggle' %></li>

      </ul>

      <ul class="nav pull-right header-meta">

        <li class="dropdown">
          <a class="dropdown-toggle"
             data-toggle="dropdown"
             href="#">
              <%= image_tag "search.png", alt: 'Search' %>
              <b class="caret"></b>
            </a>
          <ul class="dropdown-menu search-dropdown">
            <li>
              <%= form_tag posts_path, method: 'get', class: 'search-form' do %>
                <%= text_field_tag :q, params[:q], class: 'search-query', placeholder: 'Search' %>
              <%= submit_tag "Search", name: nil, class: 'search-submit' %>
              <% end %>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <a class="dropdown-toggle"
             data-toggle="dropdown"
             href="#">
              <%= image_tag "question.png", alt: 'Information', title: 'Information' %>
              <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Contact", new_contact_path %></li>
            <li><%= link_to "About", about_path %></li>
            <% if user_signed_in? %>
              <li class="divider"></li>
              <li><%= link_to "New Category", new_category_path %></li>
              <li><%= link_to "New Post", new_post_path %></li>
              <li><%= link_to "New Gear Guide", new_gear_guide_path %></li>
              <li><%= link_to "New Internal Category", new_internal_category_path %></li>
              <li><%= link_to "New Retailer", new_retailer_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
              <li><%= link_to "Edit User", edit_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_logo.html.erb
<div id="logo-container">
  <div class="container">
    <div class="row">
      <div class="span6 logo">
        <h1><%= link_to image_tag('logo.jpg', alt: 'Backpacking Talk', title: 'Backpacking Talk'), root_path %></h1>
      </div>
      <div class="span6 logo-ad">
        <% ad = Ad.offset(rand(Ad.count)).first %>
        <%= link_to image_tag(ad.ad_content), ad.ad_url, target: '_blank', rel: 'nofollow' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_newsletter.html.erb
<div class="newsletter">
  <div class="newsletter-click newsletter-prompt">
    The Best Newsletter You're Not (Yet) Subscribed To
    <%= image_tag 'arrow.png', class: 'newsletter-arrow' %>
  </div>
  <div class="newsletter-expand newsletter-content">
    <%= form_tag newsletters_newsletter_sign_up_path, method: 'get', class: 'newsletter-form' do %>
      <div class="newsletter-inputs">
        <%= text_field_tag :first_name, params[:first_name], placeholder: 'First Name' %>
        <%= text_field_tag :last_name, params[:last_name], placeholder: 'Last Name' %>
        <%= text_field_tag :email_address, params[:email_address], placeholder: 'Email Address' %>
      </div>
      <%= submit_tag "Subscribe", class: 'newsletter-submit' %>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <ul class="nav nav-tabs sidebar-nav-tabs">
    <li><a href="#forever" data-toggle="tab" id="sidebarContentTab" class="all-time-tab">
      <%= image_tag 'heart.png', alt: 'all time most popular' %>
      <p>ALL TIME</p>
    </a></li>
    <li class="active"><a href="#month" data-toggle="tab" id="sidebarContentTab" class="popular-tab">
      <%= image_tag 'month.png', alt: 'popular this month' %>
      <p>POPULAR</p>
    </a></li>
    <li><a href="#reviews" data-toggle="tab" id="sidebarContentTab" class="gear-tab">
      <%= image_tag 'gear.png', alt: 'latest gear reviews' %>
      <p>GEAR REVIEWS</p>
    </a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade" id="forever">
      <%= render "shared/tabs/forever" %>
    </div>

    <div class="tab-pane fade active in" id="month">
      <%= render "shared/tabs/month" %>
    </div>

    <div class="tab-pane fade" id="reviews">
      <%= render "shared/tabs/reviews" %>
    </div>
  </div>

  <% unless params[:controller] == 'statics' and params[:action] == 'results' %>
    <div class="product-search-wrapper">
      <div class="product-search-form-wrapper">
        <%= form_tag results_path, method: 'get', class: 'product-search-form' do %>
          <%= text_field_tag :q, params[:q], class: 'product-search-query', placeholder: 'Product Search' %>
          <%= submit_tag "Search", name: nil, class: 'product-search-submit my-btn' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <h2 class="h2-margin-left">Daily Gear Deals</h2>
  <ul class="dotd-list">
    <% Dotd.find_each do |deal| %>
      <li>
        <a href="<%= deal.buy_url %>", target="_blank", rel="nofollow">
          <%= image_tag deal.small_image_url, alt: deal.proper_product_name, title: deal.proper_product_name, class: 'product-pic' %>
          <%= image_tag "#{deal.merchant_name.gsub('.com','').downcase}.png", class: 'favicon' %>
          <%= content_tag :span, truncate(deal.proper_product_name, length: 40, omission: '..'), class: 'deal-title' %>
          <%= content_tag :span, "$#{deal.sale_price}", class: 'deal-sale-price' %>
          <div class="deal-meta">
            <%= content_tag :i, "Reg. $#{deal.retail_price}", class: 'deal-retail-price' %>
            <%= content_tag :span, "#{deal.percent_off}% off!", class: 'deal-percent-off' %>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
  <h2 class="h2-margin-left">Post Categories</h2>
  <ul class="post-tags">
    <% Category.order('tagged_posts DESC').each do |category| %>
      <% if category.tagged_posts > 0 %>
        <li>
          <a href="<%= category_path(category) %>" class="<%= cycle('odd', 'even') %>">
            <%= category.name %> (<%= category.tagged_posts %>)
          </a>
        </li>
      <% end %>
    <% end %>
  </ul>

</div>