config/routes.rb
Blog::Application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "newsletters/newsletter_sign_up"

  root :to => "statics#home"

  get "/about", to: 'statics#about'
  get 'feed', to: 'posts#feed', as: 'feed'
  get "backpacking-brands", to: 'statics#brands', as: 'brands'
  get 'results', to: 'statics#results', as: 'results'

  resources :gear_guides, path: 'gear-guides', except: :index
  resources :posts do
    collection do
      get 'section/:section', to: 'posts#section', as: 'section', constraints: proc { |req| ['backpacking', 'gear', 'food', 'photography'].include?(req.params[:section]) }
    end
  end
  resources :contact, only: [:new, :create], path: 'contact'
  resources :categories, except: :index
  resources :retailers, except: [:index, :show]
  resources :internal_categories, except: [:index, :show]

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    @posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
  end

  def about
  end

  def brands
    @brands = Retailer.all
    @brands = @brands.where('cottage_industry = ?', true) if params[:cottage].present?
    @brands = @brands.joins(:internal_categories).where(internal_categories: {id: params[:gear].to_i}) if params[:gear].present?
    @brands = @brands.sort_by { |b| b.name }
    @created = Retailer.order('created_at ASC').first.created_at
    @updated = Retailer.order('updated_at DESC').first.updated_at
  end

  def results
    if params[:q].present?
      if params[:page].present?
        offset = (params[:page].to_i * 20) - 20
      else
        offset = 0
      end
      url = "http://www.avantlink.com/api.php?affiliate_id=31645&module=ProductSearch&output=xml&website_id=145073&search_term=#{CGI.escape(params[:q])}&search_results_fields=Merchant+Name%7CProduct+Name%7CBrand+Name%7CRetail+Price%7CSale+Price%7CThumbnail+Image%7CBuy+URL%7CPrice+Discount+Percent%7CMatch+Result&search_results_base=#{ offset }&search_results_count=20"

      require 'nokogiri'
      require 'open-uri'

      data = Nokogiri::XML(open(url))
      @results = data.xpath('//Table1')
      if @results.present?
        total_results = @results.first.xpath('Match_Result').text.gsub(/\d+ of /, '').to_i
        @last_page = total_results / 20.to_f == total_results / 20 ? total_results / 20 : total_results / 20 + 1
        @last_page = 10 if @last_page > 10
        @current_page = params[:page].present? ? params[:page].to_i : 1
      end
    end
  end
end

app/helpers/statics_helper.rb
module StaticsHelper

  def search_product_name(result)
    brand = result.xpath('Brand_Name').text
    product = result.xpath('Product_Name').text
    if product.downcase.include?(brand.downcase)
      name = product
    else
      name = product.downcase.gsub(brand.downcase, '')
      name = brand + ' ' + name.titleize
    end
  end
end

app/views/statics/about.html.erb
<% provide(:title, "About Backpacking Talk") %>
<% provide(:desc, "Find out all about Backpacking Talk, what makes it so awesome, and who the great and benevolent leader of Backpacking Talk is") %>
<% provide(:canonical, about_url) %>

<h1>About Backpacking Talk</h1>

<%= image_tag 'stu-about.jpg', alt: 'Stu', class: 'about-pic' %>

<p>Backpacking Talk is all about the great activity that is backpacking. It's about trip reports, the ups and downs of backpacking food, taking great pictures in the outdoors, and just trying to have the best time possible out in nature.</p>

<p>Backpacking Talk is written by me, Stu. I'm from the South West of British Columbia, Canada, where there are plenty of mountains and trails to explore and keep me entertained. That's me in the picture on the right, having fun in the outdoors. I'm in my late 20s, and did a bit of outdoor exploring when I was younger, but have gotten more serious about it lately. I like short trips, as opposed to long and grueling ones, as well as scrambling up peaks and spending time in the alpine. Forests are okay too.</p>

<p>Besides backpacking I'm a big fan of good food, a great book and skiing when there's snow on the ground.</p>

<p>If you want to know more, or just get in touch, head over to the <%= link_to "contact page", new_contact_path %>.</p>

app/views/statics/brands.html.erb
<% provide(:title, "Camping and Backpacking Brands") %>
<% provide(:desc, "A comprehensive list of camping and backpacking brands, with options to sort for those in the cottage industry, as well as by gear type manufactured, such as sleeping bags, backpacks or tents") %>
<% provide(:canonical, brands_url) %>

<% content_for :head do %>
  <meta property="og:title" content="Camping and Backpacking Brands" />
  <meta property="og:type" content="article" />
  <meta property="og:description" content="A comprehensive list of camping and backpacking brands, with options to sort for those in the cottage industry, as well as by gear type manufactured, such as sleeping bags, backpacks or tents" />
  <meta property="og:site_name" content="Backpacking Talk" />
  <meta property="og:url" content="<%= brands_url %>" />

  <meta property="article:published_time" content="<%= @created %>" />
  <meta property="article:modified_time" content="<%= @updated %>" />
  <meta property="article:author" content="Stuart Morris" />
  <meta property="article:section" content="Outdoors" />
<% end %>

<div itemscope itemtype="http://schema.org/Article">
  <meta itemprop="datePublished" content="<%= @created %>">
  <meta itemprop="dateModified" content="<%= @updated %>">
  <meta itemprop="author" content="Stuart Morris">

  <h1 itemprop="headline">Camping and Backpacking Brands</h1>

  <div class="gear-guide-well">
    Are we missing your favorite backpacking brand? <%= link_to "Let us know!", new_contact_path %>
  </div>

  <div class="well">
    <%= form_tag brands_path, method: 'get', class: 'brand-select-form' do %>
      <%= label_tag :cottage, "Cottage Industy Only" %>
      <%= check_box_tag :cottage, {}, params[:cottage], class: 'brand-cottage-check' %>
      <%= label_tag :gear, "Only Makers Of" %>
      <%= select_tag :gear, options_for_select(InternalCategory.all.map { |category| [category.name, category.id]}, selected: params[:gear]), { include_blank: true, class: 'brand-gear-select' } %>
      <%= submit_tag "Sort", name: nil, class: 'brand-submit my-btn' %>
    <% end %>
  </div>

  <div itemprop="articleBody">

    <% @brands.each do |brand| %>

      <h2 class="brand-h2"><%= brand.name %></h2>
      <% if brand.cottage_industry? %>
        <%= image_tag 'cottage.png', alt: 'Cottage Industry', class: 'cottage-pic' %>
      <% end %>
      <br>
      <%= link_to brand.url.gsub('http://', ''), brand.url %>
      <br>
      <% if can? :edit, brand %>
        <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_retailer_path(brand) %>
        <%= link_to '<i class="icon-remove"></i> Delete'.html_safe, brand, method: :delete, data: { confirm: 'Are you sure?' } %>
        <br>
      <% end %>

      <% if brand.what_they_say.present? %>
        <div class="brand-text">
          <h3>About</h3>
          <%= simple_format(brand.what_they_say) %>
        </div>
      <% end %>
      <div class="brand-categories">
        <h3>What They Make</h3>
        <table>
          <% brand.internal_categories.each do |category| %>

            <tr>
              <td class="brand-category-name">
                <% if category.gear_guides.present? %>
                  <%= link_to category.name, gear_guide_path(category.gear_guides.first) %>
                <% else %>
                  <%= category.name %>
                <% end %>
              </td>
              <% if brand.avantlink_searchable? %>
                <td class="brand-category-indicator">
                  <%= link_to image_tag('search-link.png'), results_path(q: "#{brand.name} #{category.name}"), class: 'tooltip-me', :'data-toggle' => "tooltip", title: "Search for #{category.name} by #{brand.name}" %>
                </td>
              <% end %>
            </tr>

          <% end %>
        </table>
      </div>

      <br><br><br>

    <% end %>

  </div>

</div>

<script type="text/javascript">
  $('.tooltip-me').tooltip();
</script>

app/views/statics/home.html.erb
<% provide(:title, "home") %>
<% provide(:desc, "") %>
<% provide(:canonical, root_url) %>

<% @posts.each do |post| %>

  <h2><%= link_to post.title, post_path(post) %></h2>

  <div class="meta-well">
    <span class="post-meta-unit">
      <i class="icon-calendar"></i>
      <%= content_tag :span, pretty_date(post.created_at), class: 'post-date' %>
    </span>

    <span class="post-meta-unit">
      <i class="icon-tags"></i>
      <%= post.categories.map { |c|
              "<a href=\"#{category_path(c)}\">#{c.name}</a>"
             }.join(', ').html_safe %>
    </span>
  </div>

  <div class="post-header-pic">
    <%= image_tag post.pic_large_url, alt: post.picture_alt_text, title: post.picture_alt_text %>
  </div>

  <div class="post-content">
    <%= truncate_html(post.content.gsub('<p>[[ad#1]]</p>', ''), length: 500, omission: ' ...') %>
    <br>
    <%= link_to "Continue Reading <i class=\"icon-arrow-right icon-white\"></i>".html_safe, post_path(post), class: 'read-more-link my-btn' %>
  </div>
  <br>
  <br>

<% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/statics/results.html.erb
<% provide(:title, "Search Results for '#{params[:q]}'") %>
<% provide(:canonical, results_url) %>

<% if params[:q].present? %>

<h1>Search Results for '<%= params[:q] %>'</h1>

<div class="product-search-wrapper">
  <div class="product-search-form-wrapper">
    <%= form_tag results_path, method: 'get', class: 'product-search-form' do %>
      <%= text_field_tag :q, params[:q], class: 'product-search-query', placeholder: 'Product Search' %>
      <%= submit_tag "Search", name: nil, class: 'product-search-submit my-btn' %>
    <% end %>
  </div>
</div>

  <% if @results.present? %>

    <ul class="product-search-results">

      <% @results.each do |result| %>

        <li>

          <div class="result-img">
            <%= link_to image_tag(result.xpath('Thumbnail_Image').text, alt: search_product_name(result)), result.xpath('Buy_URL').text, rel: 'nofollow' %>
          </div>

          <div class="result-meta">
            <%= link_to result.xpath('Product_Name').text, result.xpath('Buy_URL').text, rel: 'nofollow', class: 'product-name' %>

            <span class="result-reg-price"><%= result.xpath('Retail_Price').text %></span>

            <% if result.xpath('Sale_Price').text.gsub('$','').to_i < result.xpath('Retail_Price').text.gsub('$','').to_i %>
              <span class="result-sale-price"><%= result.xpath('Sale_Price').text %> (<%= result.xpath('Price_Discount_Percent').text %> off!)</span>
            <% end %>
          </div>

          <span class="results-merchant"><%= result.xpath('Merchant_Name').text %></span>

        </li>

      <% end %>

    </ul>

    <div class="pagination">
      <ul>
        <li>
          <% if params[:page].blank? or params[:page].to_i == 1 %>
            <span class="page-inactive"><i class="icon-white icon-arrow-left"></i> Previous</span>
          <% else %>
            <%= link_to "<i class=\"icon-white icon-arrow-left\"></i> Previous".html_safe, results_path(q: params[:q], page: @current_page - 1) %>
          <% end %>
        </li>
        <% @last_page.times do |i| %>
          <li>
            <% if @current_page == i + 1 %>
              <span class="page-inactive"><%= i + 1 %></span>
            <% else %>
              <%= link_to i + 1, results_path(q: params[:q], page: i + 1) %>
            <% end %>
          </li>
        <% end %>
        <li>
          <% if @current_page == @last_page %>
            <span class="page-inactive">Next <i class="icon-white icon-arrow-right"></i></span>
          <% else %>
            <%= link_to "Next <i class=\"icon-white icon-arrow-right\"></i>".html_safe, results_path(q: params[:q], page: @current_page + 1) %>
          <% end %>
        </li>
      </ul>
    </div>

  <% else %>

    <div class="well">
      Oops, we couldn't find anything for '<%= params[:q] %>'
    </div>

  <% end %>

<% else %>

  <div class="product-search-wrapper">
    <div class="product-search-form-wrapper">
      <%= form_tag results_path, method: 'get', class: 'product-search-form' do %>
        <%= text_field_tag :q, params[:q], class: 'product-search-query', placeholder: 'Product Search' %>
        <%= submit_tag "Search", name: nil, class: 'product-search-submit my-btn' %>
      <% end %>
    </div>
  </div>

  <div class="well">
    This page works better if you search for something first.
  </div>

<% end %>