config/routes.rb
Blog::Application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "newsletters/newsletter_sign_up"

  root :to => "statics#home"

  get "/about", to: 'statics#about'
  get 'feed', to: 'posts#feed', as: 'feed'
  get "backpacking-brands", to: 'statics#brands', as: 'brands'
  get 'results', to: 'statics#results', as: 'results'

  resources :gear_guides, path: 'gear-guides', except: :index
  resources :posts do
    collection do
      get 'section/:section', to: 'posts#section', as: 'section', constraints: proc { |req| ['backpacking', 'gear', 'food', 'photography'].include?(req.params[:section]) }
    end
  end
  resources :contact, only: [:new, :create], path: 'contact'
  resources :categories, except: :index
  resources :retailers, except: [:index, :show]
  resources :internal_categories, except: [:index, :show]

end

app/models/post.rb
class Post < ActiveRecord::Base

  include GetFlickr
  include UpdateReviewProducts

  belongs_to :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_many :citations, dependent: :destroy

  accepts_nested_attributes_for :citations, :reject_if => lambda { |a| a[:url].blank? or a[:text].blank? }, :allow_destroy => true

  after_create :update_flickr_urls
  after_update :update_flickr_urls, if: Proc.new { |post| post.flickr_url_changed? }
  after_save :update_review_products

  validates_presence_of :title, :content, :flickr_url, :picture_alt_text, :section,
  :meta_description, :user_id, :categories

  include Tire::Model::Search
  include Tire::Model::Callbacks

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def related
    self.find_by_categories do |posts|
      posts.sort_by do |p|
        matched_categories = p.categories.find_all {|t| self.categories.include?(t)}
        matched_categories.size
      end.reverse
    end
  end

  def find_by_categories
    tag_ids = self.categories.collect{|a| a.id}
    found = Post.includes(:categorizations).where(["categorizations.category_id IN (?) AND categorizations.post_id != ?", categories, self.id]).references(:categorizations)
    if found.count > 0
      return found
    else
      return Post.order('all_time_view_count DESC').first(4)
    end
  end

  def content_with_review_ads
    if self.is_a_review?

      content_with_ads = content
      products = Product.order('sale_price DESC').where("post_id = ?", self.id)
      (3 - products.length).times { |a| products << nil } # so that the products array is always 3 entries long

      products.each_with_index do |product, i|
        unless product == nil
          content_with_ads = content_with_ads.gsub("<p>[[ad##{i + 1}]]</p>",
                                "
                                  <div class=\"review-ad\">
                                    <a href=\"#{product.buy_url}\" target=\"_blank\" rel=\"nofollow\">
                                      <span class=\"review-ad-merch\">#{product.merchant_name.gsub('.com', '')}</span>
                                      <span class=\"review-ad-name\">#{product.proper_product_name}</span>
                                      <span class=\"review-ad-price #{product.sale? ? 'review-ad-sale' : ''}\">#{product.lowest_price}</span>
                                    </a>
                                  </div>
                                ")
        else
          content_with_ads = content_with_ads.gsub("<p>[[ad##{i + 1}]]</p>", "")
        end
      end
      return content_with_ads
    else
      content
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  authorize_resource except: [:section, :feed]

  include PostCount # for unless bot? method in private

  # GET /posts
  # GET /posts.json
  def index
    if params[:q].present?
      @posts = Post.search(params[:q]).map(&:id)
      @groups = Post.find(@posts).in_groups_of(2, false).paginate(page: params[:page], per_page: 4)
    else
      redirect_to root_path
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    impression_count(@post)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.citations.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  def section
    authorize! :read_section, :section
    @section = params[:section]
    @groups = Post.order('created_at DESC').where("section = ?", @section).in_groups_of(2, false).paginate(page: params[:page], per_page: 4)
  end

  def feed
    authorize! :read_feed, :feed
    @posts = Post.order('created_at DESC')

    respond_to do |format|
      format.atom
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :pic_thumbnail_url, :pic_large_url, :pic_large_square_url, :pic_medium_url, :flickr_url, :all_time_view_count, :monthly_view_count, :picture_alt_text, :section, :meta_description, :stars, :is_a_review, :last_upated_products_for_review, :pictures_attributes, citations_attributes: [:id, :url, :text, :_destroy], category_ids: [])
    end

    def impression_count(post)
      unless bot?(request.user_agent)
        post.update_attributes(monthly_view_count: post.monthly_view_count + 1,
                               all_time_view_count: post.all_time_view_count + 1)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/views/posts/_citation_fields.html.erb
<div class="field-block">
  <h4>Citation</h4>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <%= f.hidden_field :_destroy %>
  <p class="remove-citation-btn"><%= link_to_remove_fields "remove", f %></p>
</div>

app/views/posts/_form.html.erb
<br>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well">

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <br>
    <div class="well">
      <ul>
        <li>ad insertion format is [[ad#1]] (3 total)</li>
        <li>Place ads: One after intro, middle, before conclusion</li>
        <li>Fancybox pics: class 'fancybox', link to large pic with small one as link content</li>
        <li>available classes: 'img-right'</li>
      </ul>
    </div>

    <div class="field">
      <h3>Categories</h3>
      <%= hidden_field_tag "post[category_ids][]", nil %>
      <% Category.find_each do |category| %>
        <%= check_box_tag "post[category_ids][]", category.id, @post.category_ids.include?(category.id), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name %><br>
      <% end %>
    </div>

    <h3>Picture</h3>
    <div class="field">
      <%= f.label :flickr_url, "Flickr URL (must have trailing slash)" %><br>
      <%= f.text_field :flickr_url %>
    </div>
    <div class="field">
      <%= f.label :picture_alt_text %><br>
      <%= f.text_field :picture_alt_text %>
    </div>
    <div>
      <%= f.fields_for :citations do |citation| %>
        <%= render 'citation_fields', :f => citation %>
      <% end %>
      <p class="add-citation-btn"><%= link_to_add_fields "Add Citation", f, :citations %></p>
    </div>

    <h3>Review</h3>
    <div class="field">
      <%= f.check_box :is_a_review %>
      <%= f.label :is_a_review %>
    </div>
    <div class="field">
      <%= f.label :stars, "Review Stars" %><br>
      <%= f.select :stars, options_for_select([1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0], selected: @post.stars.to_s), { include_blank: true } %>
    </div>

    <h3>Post Meta</h3>
    <div class="field">
      <%= f.label :section %><br>
      <%= f.select :section, [['Backpacking', 'backpacking'],
                              ['Gear', 'gear'],
                              ['Food', 'food'],
                              ['Photos', 'photos']] %>
    </div>
    <div class="field">
      <%= f.label :meta_description %><br>
      <%= f.text_field :meta_description %>
    </div>
    <br>

    <div class="actions">
      <%= f.submit 'Create Post', class: 'my-btn' %>
    </div>
  </div>
<% end %>

<script>CKEDITOR.replace('post[content]');</script>

app/views/posts/edit.html.erb
<h1>Editing '<%= @post.title %>'</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% provide(:title, "Search Reults for '#{params[:q].to_s}'") %>
<% provide(:canonical, posts_url) %>

<h1>Search Results for '<%= params[:q] %>'</h1>

<%= render partial: 'shared/group', collection: @groups %>

<%= will_paginate @groups, renderer: BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/section.html.erb
<% provide(:title, "Posts in the #{@section.titleize} Section") %>
<% provide(:desc, "Read all the posts in the #{@section.titleize} section on Backpacking Talk") %>
<% provide(:canonical, section_posts_url(@section)) %>

<h1><%= @section.titleize %> Section</h1>


<%= render partial: 'shared/group', collection: @groups %>


<%= will_paginate @groups, renderer: BootstrapPagination::Rails %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<% provide(:desc, @post.meta_description) %>
<% provide(:canonical, post_url(@post)) %>
<% content_for :head do %>
  <meta property="og:title" content="<%= @post.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:description" content="<%= @post.meta_description %>" />
  <meta property="og:site_name" content="Backpacking Talk" />
  <meta property="og:url" content="<%= post_url(@post) %>" />
  <meta property="og:image" content="<%= @post.pic_medium_url %>" />

  <meta property="article:published_time" content="<%= @post.created_at %>" />
  <meta property="article:modified_time" content="<%= @post.updated_at %>" />
  <meta property="article:author" content="Stuart Morris" />
  <meta property="article:section" content="Outdoors" />
<% end %>

<div itemscope itemtype="http://schema.org/BlogPosting">

  <div class="social-arrow">
    <%= image_tag("share.png", alt: 'show share buttons', title: 'show share buttons', class: 'social-arrow-img')  %>
  </div>

  <div class="social-bar">
    <div class="social-button">
      <div id="fb-root"></div>
      <div class="fb-like" data-href="<%= post_url(@post) %>" data-send="false" data-layout="box_count" data-width="55" data-show-faces="false"></div>
    </div>
    <div class="social-button">
      <su:badge layout="5" location="<%= post_url(@post) %>"></su:badge>
    </div>
    <div class="social-button">
      <div class="g-plusone" data-size="tall" data-href="<%= post_url(@post) %>"></div>
    </div>
    <div class="social-button">
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= post_url(@post) %>" data-via="stuwashere" data-count="vertical">Tweet</a>
    </div>
    <div class="social-button">
      <a href="//pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" ><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
    </div>
  </div>

  <h1 itemprop="headline"><%= @post.title %></h1>
  <meta itemprop="image" content="<%= @post.pic_large_url %>" id="itemPropImage">
  <meta itemprop="thumbnailUrl" content="<%= @post.pic_thumbnail_url %>" id="itemPropThumb">
  <meta itemprop="author" content="Stuart Morris" id="itemPropAuthor">

  <div class="meta-well">
    <span class="post-meta-unit">
      <i class="icon-calendar"></i>
      <time itemprop="datePublished" datetime="<%= @post.created_at %>" id="itemPropDate">
        <%= content_tag :span, pretty_date(@post.created_at), class: 'post-date' %>
      </time>
    </span>

    <span class="post-meta-unit">
      <i class="icon-tags"></i>
      <%= @post.categories.map { |c|
              "<a href=\"#{category_path(c)}\">#{c.name}</a>"
             }.join(', ').html_safe %>
    </span>

    <% if can? :edit, @post %>

      <span class="post-meta-unit">
        <i class="icon-edit"></i>
        <%= link_to 'Edit', edit_post_path(@post) %>
      </span>

      <span class="post-meta-unit">
        <i class="icon-remove"></i>
        <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>

    <% end %>
  </div>

  <div class="post-header-pic">
    <%= link_to image_tag(@post.pic_large_url, alt: @post.picture_alt_text), @post.pic_large_url, class: 'fancybox' %>
  </div>

  <% if @post.citations.present? %>

    <div class="post-citations">
      <div class="citation-link">
        <p>Picture Sources</p>
        <i class="icon-chevron-down citation-chevron"></i>
      </div>

      <div class="citation-dropdown">
        <ul>
          <% @post.citations.each do |citation| %>
            <li>
              <%= link_to citation.text, citation.url, rel: 'nofollow', target: '_blank' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  <% end %>

  <% if @post.stars.present? %>
    <div class="post-review-stars" itemprop="review" itemscope itemtype="http://schema.org/Review">
      <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">

        <meta itemprop="worstRating" content = "1">
        <meta itemprop="ratingValue" content = "<%= @post.stars %>">
        <meta itemprop="bestRating" content = "5">

        <% @post.stars.to_i.times do %>
          <%= image_tag "star_full.jpg" %>
        <% end %>

        <% if @post.stars.to_i + 0.5 == @post.stars %>
          <%= image_tag "star_half.jpg" %>
        <% end %>

        <% (5 - (@post.stars + 0.5).to_i).times do # + 0.5 to account for the possible half star %>
          <%= image_tag "star_empty.jpg" %>
        <% end %>
      </div>

      <div itemprop="itemReviewed" itemscope itemtype="http://schema.org/Thing">
        <meta itemprop="name" content = "<%= @post.title.gsub(' Review', '') %>">
      </div>
      <meta itemprop="reviewBody" itemref="itemPropText">
      <meta itemprop="image" itemref="itemPropImage">
      <meta itemprop="thumbnailUrl" itemref="itemPropThumb">
      <meta itemprop="author" itemref="itemPropAuthor">
      <time itemprop="datePublished" itemref="itemPropDate"></time>

    </div>
  <% end %>

  <div class="post-content" itemprop="text" id="itemPropText">
    <%= @post.content_with_review_ads.html_safe %>
  </div>

  <div class="bottom-of-post">

    <div class="newsletter">
      <div class="newsletter-prompt">
        Newsletter: Extra Content, Exclusive Offers And More
      </div>
      <div class="newsletter-content">
        <%= form_tag newsletters_newsletter_sign_up_path, method: 'get', class: 'newsletter-form' do %>
          <div class="newsletter-inputs">
            <%= text_field_tag :name, params[:name], placeholder: 'Name' %>
            <%= text_field_tag :email_address, params[:email_address], placeholder: 'Email Address' %>
          </div>
          <%= submit_tag "Subscribe", class: 'newsletter-submit' %>
        <% end %>
      </div>
    </div>

    <h2 class="h2-margin-left">Related Posts</h2>

    <% @post.related.each_with_index do |post, i| %>
      <div class="related-div <%= i == 3 ? 'last-related-pic' : '' %>">
        <a href="<%= post_path(post) %>">
          <%= image_tag post.pic_large_square_url, alt: post.picture_alt_text, title: post.picture_alt_text, class: "related-post-pic" %>
          <%= content_tag :span, post.title, class: 'related-post-title' %>
        </a>
      </div>
    <% end %>

    <h2 class="h2-margin-left">Comments</h2>

    <div class="comments">
      <div id="disqus_thread"></div>
      <script type="text/javascript">
          /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
          var disqus_shortname = 'backpackingtalk'; // required: replace example with your forum shortname

          /* * * DON'T EDIT BELOW THIS LINE * * */
          (function() {
              var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
              dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
       </script>
      <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>

  </div>

</div>